// Central Studio Registry for LooksGood
// Designed to be easily extensible for future tools and studios.

export const STUDIOS_REGISTRY = [
  {
    id: 'colors',
    name: 'Colors Studio',
    shortName: 'Colors',
    description: 'The complete creative color engine — smart custom questionnaire, harmonies, WCAG contrast, shade generator & image sampling.',
    badge: '7 Tools',
    status: 'active',
    icon: 'Palette',
    accentColor: '#7C3AED',
    bgGradient: 'from-[#6366F1] via-[#7C3AED] to-[#9333EA]',
    defaultTab: 'custom',
    tabs: [
      { id: 'custom', name: 'Smart Palette Synthesizer', icon: 'Wand2', desc: 'Choose 2, 3, 4, 5 colors & answer questions for 4 tailored palettes' },
      { id: 'palette', name: 'Palette & Harmony', icon: 'Sparkles', desc: 'Harmonic color wheel & 5-role design system' },
      { id: 'shades', name: 'Shades & Tints Scale', icon: 'Layers', desc: '50-950 Tailwind & CSS shade scale generator' },
      { id: 'contrast', name: 'WCAG Contrast Checker', icon: 'CheckCircle2', desc: 'Realtime ratio scoring, AA/AAA check & 1-click Auto-Fix' },
      { id: 'imagePicker', name: 'Image Color Extractor', icon: 'Image', desc: '5-pin real-time photo extractor & dominant palette' },
      { id: 'trending', name: 'Trending Palettes', icon: 'Flame', desc: '100+ curated harmonious palettes categorized by mood' },
      { id: 'export', name: 'Code & Export Center', icon: 'Code2', desc: 'CSS Variables, Tailwind Config, SCSS, JSON & SVG' },
    ],
  },
  {
    id: 'typography',
    name: 'Typography Studio',
    shortName: 'Typography',
    description: 'Complete typography workspace — Google fonts library, pairing engine, modular type scales & live editorial preview.',
    badge: '6 Tools',
    status: 'active',
    icon: 'Type',
    accentColor: '#DB2777',
    bgGradient: 'from-[#EC4899] via-[#DB2777] to-[#BE185D]',
    defaultTab: 'explorer',
    tabs: [
      { id: 'explorer', name: 'Font Explorer & Search', icon: 'Search', desc: '30+ Google fonts filtered by category & personality' },
      { id: 'pairings', name: 'Font Pairing Engine', icon: 'Star', desc: 'Curated heading + body pairings with harmony rationale' },
      { id: 'typeScale', name: 'Modular Type Scale', icon: 'Sliders', desc: 'Golden Ratio, Major Third & responsive hierarchy calculator' },
      { id: 'playground', name: 'Editorial & UI Playground', icon: 'LayoutGrid', desc: 'Live landing page, blog article & UI card typography tester' },
      { id: 'reverse', name: 'Reverse Pairing Finder', icon: 'ArrowRightLeft', desc: 'Pick body font to find matching headings' },
      { id: 'export', name: 'CSS & Fonts Exporter', icon: 'Code2', desc: 'Google Fonts CDN <link>, @import & Tailwind typography' },
    ],
  },
  {
    id: 'cssEffects',
    name: 'CSS & Effects Studio',
    shortName: 'CSS & Shadows',
    description: 'Modern CSS visual generators — layered box shadows, glassmorphism, glowing borders & neumorphic cards.',
    badge: 'Roadmap',
    status: 'upcoming',
    icon: 'Layers',
    accentColor: '#0284C7',
    bgGradient: 'from-[#0284C7] via-[#0EA5E9] to-[#38BDF8]',
    defaultTab: 'shadows',
    tabs: [
      { id: 'shadows', name: 'Smooth Shadow Generator', icon: 'Sliders', desc: 'Multi-layer natural ambient shadows' },
      { id: 'glass', name: 'Glassmorphism Studio', icon: 'Sparkles', desc: 'Frosted glass blur & specular borders' },
      { id: 'borders', name: 'Gradients & Glow Borders', icon: 'Code2', desc: 'Animated gradient border effects' },
    ],
  },
  {
    id: 'svgMesh',
    name: 'SVG & Mesh Studio',
    shortName: 'SVG & Mesh',
    description: 'Algorithmic design assets — organic SVG waves, blob generators, mesh gradients & noise textures.',
    badge: 'Roadmap',
    status: 'upcoming',
    icon: 'Sparkles',
    accentColor: '#059669',
    bgGradient: 'from-[#059669] via-[#10B981] to-[#34D399]',
    defaultTab: 'mesh',
    tabs: [
      { id: 'mesh', name: 'Mesh Gradient Builder', icon: 'Sliders', desc: 'Interactive 4-point generative mesh curves' },
      { id: 'waves', name: 'Organic SVG Wave Maker', icon: 'Layers', desc: 'Smooth SVG page dividers and hero waves' },
      { id: 'blobs', name: 'Dynamic SVG Blob Maker', icon: 'Sparkles', desc: 'Randomized morphing blob shapes for UI' },
    ],
  },
  {
    id: 'layoutGrid',
    name: 'Layout & Grid Studio',
    shortName: 'Grids & UI',
    description: 'Responsive layout architecture — CSS Grid visual builder, Bento layout generator & spacing systems.',
    badge: 'Roadmap',
    status: 'upcoming',
    icon: 'LayoutGrid',
    accentColor: '#EA580C',
    bgGradient: 'from-[#EA580C] via-[#F97316] to-[#FB923C]',
    defaultTab: 'bento',
    tabs: [
      { id: 'bento', name: 'Bento Grid Visualizer', icon: 'LayoutGrid', desc: 'Drag-and-drop modern Bento layout generator' },
      { id: 'grid', name: 'CSS Grid & Flex Builder', icon: 'Sliders', desc: 'Visual 12-column responsive layout builder' },
      { id: 'spacing', name: 'Spacing & 8pt Scale', icon: 'Code2', desc: 'Consistent spatial tokens for UI design systems' },
    ],
  },
];

export const getStudioById = (id) => STUDIOS_REGISTRY.find((s) => s.id === id) || STUDIOS_REGISTRY[0];
